spring:
  profiles: "dev"

info:
  app:
    name: Spring Sample Application in dev
    description: This is my first spring boot application
    version: 1.0.0
    
    
---

spring:
  profiles: "test"

info:
  app:
    name: Spring Sample Application in test
    description: This is my first spring boot application
    version: 1.0.0
    